FROM ubuntu:16.04
MAINTAINER Hardik Patel <hardikgw@gmail.com>
ENV\
	SPARK_VER=2.0.0 \
	TF_BINARY_URL=https://storage.googleapis.com/tensorflow/mac/gpu/tensorflow-0.10.0rc0-py2-none-any.whl
RUN\
	apt-get update &&\
	apt-get install -y vim curl wget default-jdk &&\
	apt-get update &&\
	wget http://d3kbcqa49mib13.cloudfront.net/spark-${SPARK_VER}-bin-hadoop2.7.tgz &&\
	tar -xvzf spark-${SPARK_VER}-bin-hadoop2.7.tgz &&\
	ln -s spark-${SPARK_VER}-bin-hadoop2.7 spark &&\
	rm spark-${SPARK_VER}-bin-hadoop2.7.tgz &&\
	apt-get install -y python-pip python-dev &&\
	pip install --ignore-installed --upgrade ${TF_BINARY_URL}
CMD	/bin/bash